# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53ff42783990b110398a65f1c370ebb55dbbb448abf979c8250088bcc3411ce8481ec17d49b15aae804ba40fbc02087448864c0464af375b59211ed5427a6031

test:
  secret_key_base: 24ad56d652b085586bfb5af1b6410a2e2a618c281138653d25f1aa9da4d84f0fa83f7c6a07dfd25b900551fee9d371b30827802cef63a75817c69a86aa661d67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
